name: Django Tests

on:
  # Run the workflow on every push or pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up the environment variables for Django using GitHub Secrets
      - name: Set environment variables
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DEBUG=${{ secrets.DEBUG }}" >> $GITHUB_ENV


      # Run migrations
      - name: Run migrations
        run: |
          python manage.py migrate

      # Gather static files
      - name: Gather staticfiles
        run: |
          python manage.py collectstatic --no-input

      # Run tests
      - name: Run Django tests
        run: |
          python manage.py test
